name: Update Docker Hub Description

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  docker-hub-readme:
    name: Sync README.md to Docker Hub Description
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update Repository Description on Docker Hub
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: aixerdev/pipelinex
          readme-filepath: ./README.md
